# conda env create -f environment_mxnetkeras.yml
name: mxnetkeras
channels:
  - defaults
dependencies:
  - python=3.6
  - pip
  - numpy=1.14.6 # requirement of mxnet-cu90mkl
  - pytables=3.4.4
  - h5py=2.9.0
  - scipy=1.2.0
  - pandas=0.24.1
  - scikit-learn=0.20.2
  - matplotlib=3.0.2
  - seaborn=0.9.0
  - pytest=4.2.1
  - xlrd=1.2.0
  - openpyxl=2.6.0
  - xlwt=1.3.0
  - xarray=0.11.3
  - dask=1.1.1
  - netCDF4=1.4.2
  - bottleneck=1.2.1
  - mkl-service=1.1.2
  - zlib=1.2.11
  - sympy=1.3
  - numba=0.42.0
  - jupyter=1.0.0
  - cython=0.29.5
  - pip:
    - mxnet==1.3.1
    - keras-mxnet==2.2.4.1
    - watermark

# pip install mxnet-cu90
# pip install mxnet-cu90mkl
